version: "3"
volumes:
  mariadb:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/mannahri/data/mariadb
  wordpress :
    driver: local
    driver_opts:
        o: bind
        type: none
        device : /home/mannahri/data/wordpress
networks:
  containes_net:
    driver: bridge
services:
    mariadb:
        container_name: mariadb
        env_file: .env
        build:
            context: ./requirements/mariadb/
            args:
                DB_NAME: ${DB_NAME}
                DB_HOST: ${DB_HOST}
                DB_USER: ${DB_USER}
                MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - containes_net
    wordpress:
        depends_on:
            - mariadb 
        container_name: wordpress
        build:
            context: ./requirements/wordpress/
        env_file: .env
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - containes_net
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx/
        ports: 
            - 443:443
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - containes_net