version: "3"
#depend on 
volumes:
  mariadb:
    driver: local
    driver_opts:
      device: ./data/mariadb
  wordpress :
    driver : local
    driver_opts :
      device : ./data/wordpress
networks:
  containes_net:
    driver: bridge
services:
    nginx:
        depends_on:
            - mariadb 
        build:
            context: ./requirements/nginx/
        container_name: nginx
        ports: 
            - 443:443
        restart: always
        volumes:
            - ./wordpress:/var/www/html
        networks:
            - containes_net
    mariadb:
        build:
            context: ./requirements/mariadb/
            args:
                DBname: poza
                THE_USER: mannahri
                MARIADB_ROOT_PASSWORD: simopoza12345
        container_name: mariadb
        restart: always
        volumes:
            - ./mariadb:/var/lib/mysql
        networks:
            - containes_net
    wordpress:
        depends_on:
            - mariadb 
        build:
            context: ./requirements/wordpress/
            args:
                DB_NAME: poza
                DB_USER: mannahri
                DB_PASSWORD: simopoza12345
                DB_HOST: simo
                AD_USER: mannahri
                AD_PASSWORD: onepieceisgoat123
                email: mohammedannahri18@gmail.com
                WP_USER: mannahri
                WP_EMAIL:  mannahri@student.1337.ma
                WP_PASSWORD: dimadimaraja123
        container_name: wordpress
        restart: always
        volumes:
            - ./wordpress:/var/www/html
        networks:
            - containes_net
