version: "3"
volumes:
  mariadb:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ${PWD}/data/db
  wordpress :
    driver: local
    driver_opts:
        o: bind
        type: none
        device : ${PWD}/data/wp
networks:
  containes_net:
    driver: bridge
services:
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb/
            args:
                DB_NAME: poza
                DB_HOST: mariadb
                DB_USER: mannahri
                MARIADB_ROOT_PASSWORD: simopoza12345
        env_file: .env
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - containes_net
    wordpress:
        depends_on:
            - mariadb 
        container_name: wordpress
        build:
            context: ./requirements/wordpress/
        env_file: .env
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - containes_net
    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx/
        ports: 
            - 443:443
        restart: always
        volumes:
            - wordpress:/var/www/html
        networks:
            - containes_net